### PR TITLE
ci: setup lint-staged

### PR DESCRIPTION
**Pull request by BrandonWu500**

### CODE REVIEW

**Review by brandonwu501 — COMMENTED** [review]
Have you tried testing this out in a commit to make sure it works? It looks right, but it might help to confirm.

**Comment by BrandonWu500** [comment]
Just tested it, and can confirm it is working!

**Review by brandonwu501 — COMMENTED** [review]
Great!

**Review by brandonwu501 — COMMENTED** [review]
Great!

**Review by brandonwu501 — APPROVED** [review]

**Pull request merged**
